language: python
sudo: false
addons:
  apt:
    packages:
      - gcc
      - python-dev
      - python3-dev
      - libgit2-dev
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install cffi
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest
