language: python
sudo: required
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - sudo apt-get update
  - sudo apt-get install gcc python-dev python3-dev libgit2-dev
  - pip install cffi
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest
